const directors = [
  'Director',
  'Series Director',
  'Co-Director',
  'Creative Director',
];

const writers = [
  'Writer',
  'Staff Writer',
  'Author',
  'Script',
  'Scenario Writer',
  'Co-Writer',
  'Script Editor',
  'Script Coordinator',
  'Creator',
  'Adaptation',
  'Screenplay',
  'Screenstory',
  'Original Film Writer',
  'Story',
  'Teleplay',
  'Short Story',
  'Book',
  'Novel',
  'Graphic Novel',
  'Graphic Novel Illustrator',
];

const editors = [
  'Supervising Film Editor',
  'Editor',
  'Co-Editor',
  'Second Film Editor',
  'Online Editor',
  'Assistant Editor',
  'Additional Editing',
];

const colour = [
  'Senior Colorist',
  'Colorist',
  'Color Grading',
  'Digital Colorist',
  'Additional Colorist',
  'Color Assistant',
  'Digital Intermediate Colorist',
  'Telecine Colorist',
  'Commissioning Editor',
  'Color Timer',
  'Digital Color Timer',
];

const AD = [
  'First Assistant Director',
  'Second Assistant Director',
  'Second Second Assistant Director',
  'Additional Second Assistant Director',
  'Third Assistant Director',
  'Additional Third Assistant Director',
  'Assistant Director',
];

const storyboarding = [
  'Storyboarding',
  'Additional Storyboarding',
  'Digital Storyboarding',
  'Storyboard Assistant',
  'Storyboard Designer',
  'Storyboard',
  'Storyboard Artist',
  'Story Artist',
];

const production = [
  'Head of Production',
  'Executive Producer',
  'Co-Executive Producer',
  'Executive Producer\'s Assistant',
  'Production Supervisor',
  'Producer',
  'Associate Producer',
  'Co-Producer',
  'Producer\'s Assistant',
  'Line Producer',
  'Production Assistant',
  'Production Runner',
  'Production Trainee',
  'Production Design',
  'Production Designer',
  'Production Controller',
  'Additional Production Assistant',
  'Editorial Production Assistant',
];

const casting = [
  'Casting Director',
  'Casting Coordinator',
  'Casting Assistant',
  'Casting Associate',
  'Casting',
  'Casting Consultant',
  'Additional Casting',
  'Location Casting',
  'Locale Casting Director',
  'Local Casting',
  'Extras Casting',
  'Extras Casting Coordinator',
  'Extras Casting Assistant',
  'Assistant Extras Casting',
  'Background Casting Director',
  'Original Casting',
];

const costume = [
  'Key Costumer',
  'Key Set Costumer',
  'Set Costumer',
  'Costume Designer',
  'Assistant Costume Designer',
  'Co-Costume Designer',
  'Wardrobe Master',
  'Costume Consultant',
  'Costume Coordinator',
  'Wardrobe Coordinator',
  'Costume Supervisor',
  'Wardrobe Supervisor',
  'Costume Design',
  'Wardrobe Designer',
  'Costume Standby',
  'Costume Assistant',
  'Wardrobe Assistant',
  'Additional Wardrobe Assistant',
  'Costume Illustrator',
  'Costume Set Supervisor',
  'Principal Costumer',
  'Costumer',
  'Wardrobe Specialized Technician',
  'Textile Artist',
];

const SFX = [
  'Special Effects Technician',
  'Special Effects Coordinator',
  'Special Effects Supervisor',
  'Key Special Effects',
  'Special Effects',
  'Special Effects Assistant',
  'Special Effects Manager',
  'Special Effects Key Makeup Artist',
  'Special Effects Makeup Artist',
  'Special Effects Best Boy',
];

const VFX = [
  'Executive Visual Effects Producer',
  'Senior Visual Effects Supervisor',
  'Visual Effects Director',
  'Visual Effects Supervisor',
  'VFX Supervisor',
  'Visual Effects Producer',
  'Visual Effects Coordinator',
  'Visual Effects Editor',
  'Visual Effects Assistant Editor',
  'Visual Effects Compositor',
  'Visual Effects Technical Director',
  'Visual Effects Production Assistant',
  'Visual Effects Design Consultant',
  'Visual Effects Production Manager',
  'Visual Effects Designer',
  'Visual Effects Art Director',
  'Visual Effects',
  'VFX Production Coordinator',
  'VFX Artist',
  'VFX Editor',
  'VFX Director of Photography',
  'VFX Lighting Artist',
];

const animation = [
  'Animation Technical Director',
  'Animation Director',
  'Animation Supervisor',
  'Animation Coordinator',
  'Animation Department Coordinator',
  'Animation Fix Coordinator',
  'Animation Production Assistant',
  'Animation Manager',
  'Head of Animation',
  'Key Animation',
  'Supervising Animation Director',
  'Animation',
  'Supervising Animator',
];

const drivers = [
  'Cast Driver',
  'Production Driver',
  'Driver',
];

const pyro = [
  'Pyrotechnic Supervisor',
  'Pyrotechnician',
];

const hairAndMakeup = [
  'Hair Department Head',
  'Hair Supervisor',
  'Hair Designer',
  'Hair Setup',
  'Key Hair Stylist',
  'Hair Stylist',
  'Hairstylist',
  'First Assistant Hairstylist',
  'Assistant Hairstylist',
  'Additional Hairstylist',
  'Key Hairdresser',
  'Hairdresser',
  'Assistant Hairdresser',
  'Hair Assistant',
  'Makeup & Hair',
  'Makeup & Hair Assistant',
  'Daily Makeup & Hair',
  'Makeup Designer',
  'Makeup Department Head',
  'Key Makeup Artist',
  'Assistant Makeup Artist',
  'Makeup Artist',
  'First Assistant Makeup Artist',
  'Makeup Trainee',
  'Makeup Supervisor',
  'Makeup Effects Designer',
  'Extras Makeup Artist',
];

const camera = [
  'Camera Operator',
  'Steadycam',
  'Assistant Camera',
  'First Assistant Camera',
  'Additional First Assistant Camera',
  'Second Assistant Camera',
  'Additional Second Assistant Camera',
  '"A" Camera Operator',
  'First Assistant "A" Camera',
  'Second Assistant "A" Camera',
  'Third Assistant "A" Camera',
  '"B" Camera Operator',
  'First Assistant "B" Camera',
  'Second Assistant "B" Camera',
  'Third Assistant "B" Camera',
  '"C" Camera Operator',
  'First Assistant "C" Camera',
  'Second Assistant "C" Camera',
  'Third Assistant "C" Camera',
  '"D" Camera Operator',
  'First Assistant "D" Camera',
  'Second Assistant "D" Camera',
  'Third Assistant "D" Camera',
  'Aerial Camera',
  'Aerial Camera Technician',
  'Camera Department Production Assistant',
  'Dolly Grip',
  'Camera Technician',
  'Helicopter Camera',
  'Additional Camera',
  'Visual Effects Camera',
  'Steadicam Operator',
  'Camera Car',
  'Camera Trainee',
  'Camera Department Manager',
  'Third Assistant Camera',
  'Camera Supervisor',
  'Camera Loader',
  'Epk Camera Operator',
  'Camera Production Assistant',
  'Camera Intern',
  'Lighting Camera',
];

const foley = [
  'Foley Supervisor',
  'Foley Artist',
  'Assistant Foley Artist',
  'Foley Editor',
  'Foley Mixer',
  'Foley Recordist',
  'Foley Recording Engineer',
  'Foley',
];

const secondUnit = [
  'Second Unit Director',
  'Second Unit Director of Photography',
  'Second Unit Cinematographer',
  'Second Unit Location Manager',
  'Second Unit First Assistant Director',
  'Second Unit',
];

const art = [
  'Art Department Coordinator',
  'Art Department Trainee',
  'Art Department Manager',
  'Art Department Assistant',
  'Art Department Production Assistant',
  'Runner Art Department',
  'Scenic Artist',
  'Supervising Art Director',
  'Co-Art Director',
  'Second Assistant Art Director',
  'Standby Art Director',
  'Assistant Art Director',
];

const prosthetics = [
  'Prosthetic Supervisor',
  'Prosthetics',
  'Prosthetic Makeup Artist',
  'Prosthetic Designer',
  'Prosthetics Sculptor',
  'Animatronic and Prosthetic Effects',
];

const CGI = [
  'CGI Director',
  'CGI Supervisor',
  'CG Animator',
  'CG Supervisor',
  'CG Artist',
  'CG Painter',
];

const consultants = [
  'Production Consultant',
  'Military Consultant',
  'Executive Consultant',
  'Story Consultant',
  'Scientific Consultant',
  'Creative Consultant',
  'Script Consultant',
  'Editorial Consultant',
  'Medical Consultant',
  'Technical Advisor',
  'Consulting Editor',
  'Consulting Producer',
];

const lighting = [
  'Lighting Director',
  'Lighting Supervisor',
  'Chief Lighting Technician',
  'Assistant Chief Lighting Technician',
  'Lighting Technician',
  'Additional Lighting Technician',
  'Master Lighting Artist',
  'Lighting Artist',
  'Lighting Design',
  'Lighting Programmer',
  'Lighting Production Assistant',
  'Lighting Manager',
  'Lighting Coordinator',
  'Best Boy Lighting Technician',
];

const stereoscopic = [
  'Stereoscopic Supervisor',
  'Stereoscopic Technical Director',
  'Stereoscopic Coordinator',
  'Stereoscopic Editor',
];

const THREE_D = [
  '3D Director',
  '3D Supervisor',
  '3D Coordinator',
  '3D Modeller',
  '3D Artist',
  '3D Animator',
  '3D Editor',
  '3D Generalist',
];

const accountants = [
  'Production Accountant',
  'First Assistant Accountant',
  'Post Production Accountant',
  'Second Assistant Accountant',
  'Payroll Accountant',
  'Assistant Accountant',
  'Accountant',
  'Finance',
];

const music = [
  'Executive Music Producer',
  'Original Music Composer',
  'Music Director',
  'Music Supervisor',
  'Assistant Music Supervisor',
  'Music Arranger',
  'Music Producer',
  'Music Consultant',
  'Music Coordinator',
  'Music Score Producer',
  'Music Programmer',
  'Musician',
  'Additional Music',
  'Additional Soundtrack',
  'Music',
  'Supervising Music Editor',
  'Music Editor',
  'Temp Music Editor',
  'Songs',
  'Lyricist',
];

const sound = [
  'Sound Director',
  'Sound Designer',
  'Assistant Sound Designer',
  'Sound Design Assistant',
  'Music Sound Design and Processing',
  'Sound Effects Editor',
  'Sound Effects Designer',
  'Supervising Sound Editor',
  'Sound Editor',
  'Assistant Sound Editor',
  'First Assistant Sound Editor',
  'Apprentice Sound Editor',
  'Temp Sound Editor',
  'Sound Re-Recording Mixer',
  'Additional Sound Re-Recording Mixer',
  'Sound Re-Recordist',
  'Additional Sound Re-Recordist',
  'Sound Supervisor',
  'Sound Re-Recording Assistant',
  'Production Sound Mixer',
  'Additional Production Sound Mixer',
  'Sound Mixer',
  'Mixing Engineer',
  'Sound mixer',
  'Sound Mix Technician',
  'Second Assistant Sound',
  'Supervising Sound Effects Editor',
  'Sound Effects',
  'Sound Assistant',
  'Sound Recordist',
  'Sound Engineer',
  'Assistant Sound Engineer',
  'Scoring Mixer',
  'Score Engineer',
  'Sound',
  'Dolby Consultant',
  'Boom Operator',
];

const ADR = [
  'Supervising ADR Editor',
  'ADR Supervisor',
  'ADR Coordinator',
  'ADR & Dubbing',
  'ADR Editor',
  'ADR Mixer',
  'ADR Engineer',
  'ADR Recordist',
  'ADR Voice Casting',
];

const coaching = [
  'Dialect Coach',
  'Dialogue Coach',
  'Vocal Coach',
];

const rigging = [
  'Rigging Grip',
  'Rigging Gaffer',
  'Key Rigging Grip',
  'Rigging Supervisor',
];

const tranport = [
  'Transportation Captain',
  'Transportation Co-Captain',
  'Transportation Coordinator',
];

const painters = [
  'Lead Painter',
  'Standby Painter',
  'Matte Painter',
  'Set Painter',
  'Painter',
];

const dialogue = [
  'Supervising Dialogue Editor',
  'Dialogue Editor',
  'Dialogue',
  'Additional Dialogue',
  'Assistant Dialogue Editor',
]

const carpenters = [
  'Head Carpenter',
  'Key Carpenter',
  'Carpenter',
  'Standby Carpenter',
  'Supervising Carpenter',
];

const electricians = [
  'Electrician',
  'Shop Electric',
  'Daily Electrics',
  'Best Boy Electrician',
  'Best Boy Electric',
];

const dailies = [
  'Dailies Technician',
  'Dailies Manager',
  'Dailies Operator',
];

const setDressing = [
  'Set Decoration',
  'Assistant Set Decoration',
  'Set Decoration Buyer',
  'Assistant Set Decoration Buyer',
  'Lead Set Dresser',
  'Key Dresser',
  'Set Dresser',
  'Assistant Set Dresser',
  'Additional Set Dresser',
  'On Set Dresser',
  'Set Designer',
  'Set Dressing Supervisor',
  'Set Dressing Production Assistant',
  'Set Dressing Artist',
  'Set Dressing Buyer',
];

const ProductionCoordinators = [
  'Assistant Production Coordinator',
  'First Assistant Production Coordinator',
  'Second Assistant Production Coordinator',
  'Production Coordinator',
  'Trainee Production Coordinator',
  'Picture Car Coordinator',
];

const DOP = [
  'Director of Photography',
  'Additional Director of Photography',
  'Assistant Director of Photography',
  'Underwater Director of Photography',
  'Aerial Director of Photography',
  'Cinematography',
];

const construction = [
  'Construction Coordinator',
  'Construction Manager',
  'Construction Foreman',
  'Key Construction Grip',
  'Construction Buyer',
  'Construction Grip',
];

const underwater = [
  
  'Underwater Camera',
  'Underwater Gaffer',
];

const BTS = [
  'Still Photographer',
  'Additional Still Photographer',
  'Set Photographer',
  'Additional Set Photographer',
  'BTS Photographer',
  'BTS Videographer',
  'BTS Footage',
];

const compositing = [
  'Compositing Lead',
  'Compositing Artist',
  'Compositing Supervisor',
];

const supervisors = [
  'Script Supervisor',
  'Additional Script Supervisor',
  'Modelling Supervisor',
  'Layout Supervisor',
  'Truck Supervisor',
  'Quality Control Supervisor',
  'Digital Supervisor',
  'Sets & Props Supervisor',
  'I/O Supervisor',
  '2D Supervisor',
  'Story Supervisor',
  'Roto Supervisor',
  'Effects Supervisor',
  'Digital Effects Supervisor',
  'Technical Supervisor',
  'Matchmove Supervisor',
  'Character Technical Supervisor',
  'Character Modelling Supervisor',
  'Set Supervisor',
  'Sequence Supervisor',
];

const postProduction = [
  'Executive In Charge Of Post Production',
  'Post Production Producer',
  'Post-Production Manager',
  'Post Production Coordinator',
  'Post Coordinator',
  'Post Production Assistant',
  'Post Producer',
  'Post Production Technical Engineer',
  'Post Production Supervisor',
  'Post Production Consulting',
];

const props = [
  'Special Props',
  'Set Propsman',
  'Props',
  'On Set Props',
  'Sets & Props Artist',
  'Prop Maker',
  'Propmaker',
];

const SetProduction = [
  'Key Set Production Assistant',
  'Set Production Intern',
  'Set Production Assistant',
];

const location = [
  'Location Coordinator',
  'Location Manager',
  'Location Assistant',
  'Assistant Location Manager',
  'Location Production Assistant',
  'Location Scout',
];

const coordinators = [
  'Clearances Coordinator',
  'Production Office Coordinator',
  'Animal Coordinator',
  'Aerial Coordinator',
  'Playback Coordinator',
  'Security Coordinator',
  'Set Decorating Coordinator',
  'Story Coordinator',
  'Editorial Coordinator',
  'Paint Coordinator',
  'Vehicles Coordinator',
  'Armory Coordinator',
  'Schedule Coordinator',
  'Travel Coordinator',
  'Marine Coordinator',
  'Business Affairs Coordinator',
];

const stunts = [
  'Stunts',
  'Stunt Driver',
  'Utility Stunts',
  'Stunt Coordinator',
  'Stunts Coordinator',
  'Stunt Double',
];

const wranglers = [
  'Gun Wrangler',
  'Data Wrangler',
  'Vehicles Wrangler',
  'Animal Wrangler',
];

const choreography = [
  'Choreographer',
  'Associate Choreographer',
  'Fight Choreographer',
  'Martial Arts Choreographer',
];

const property = [
  'Property Master',
  'First Assistant Property Master',
  'Assistant Property Master',
  'Standby Property Master',
  'Property Buyer',
  'Property Builder',
];

const animatronics = [
  'Animatronics Designer',
  'Animatronics Supervisor',
];

const roles = [
  ...directors,
  ...writers,
  ...editors,
  ...DOP,
  ...colour,
  ...AD,
  ...storyboarding,
  ...ProductionCoordinators,
  ...production,
  ...camera,
  ...postProduction,
  ...casting,
  ...costume,
  ...animation,
  ...pyro,
  ...hairAndMakeup,
  ...secondUnit,
  ...art,
  ...prosthetics,
  ...animatronics,
  ...sound,
  ...foley,
  ...ADR,
  ...lighting,
  ...SFX,
  ...VFX,
  ...CGI,
  ...music,
  ...dailies,
  ...tranport,
  ...accountants,
  ...THREE_D,
  ...dialogue,
  ...coaching,
  ...rigging,
  ...painters,
  ...underwater,
  ...stereoscopic,
  ...setDressing,
  ...construction,
  ...props,
  ...BTS,
  ...compositing,
  ...consultants,
  ...supervisors,
  ...electricians,
  ...carpenters,
  ...drivers,
  ...SetProduction,
  ...location,
  ...coordinators,
  ...stunts,
  ...choreography,
  ...wranglers,
  ...property,
  'Characters',
  'Additional Key Grip',
  'Clapper Loader',
  'Cableman',
  'Creature Design',
  'Translator',
  'Playback Singer',
  'Accounting Clerk Assistant',
  'Best Boy Grip',
  'In Memory Of',
  'Assistant Director Trainee',
  'Continuity',
  'Additional Photography',
  'Senior Animator',
  'Generalist',
  'Security',
  'Production Illustrator',
  'Systems Administrators & Support',
  'Digital Compositors',
  'Assistant Craft Service',
  'Lead Animator',
  'Chef',
  'Assistant Chef',
  'Studio Teachers',
  'Swing',
  'Director of Operations',
  'Development Manager',
  'Pilot',
  'Executive Assistant',
  'Intern',
  'Transcriptions',
  'Project Manager',
  'Musical',
  'Manager of Operations',
  'General Manager',
  'Special Sound Effects',
  'Film Processor',
  'Imaging Science',
  'Editorial Services',
  'Epk Producer',
  'EPK Editor',
  'Sequence Lead',
  'Art Direction Intern',
  'Additional Writing',
  'Production Director',
  'Controller',
  'Second Assistant Director Trainee',
  'Head of Story',
  'Digital Producer',
  'Supervising Technical Director',
  'Layout',
  'Presenter',
  'Machinist',
  'Idea',
  'Assistant Production Design',
  'Finishing Producer',
  'Original Concept',
  'Video Game',
  'Recording Supervision',
  'Second Company Grip',
  'Art Designer',
  'Stage Director',
  'Charge Scenic Artist',
  'Archival Footage Research',
  'Pipeline Technical Director',
  'Extras Dresser',
  'Information Systems Manager',
  'Creature Effects Technical Director',
  'Head of Layout',
  'Simulation & Effects Artist',
  'Contact Lens Painter',
  'Senior Generalist',
  'Executive in Charge of Finance',
  'Decorator',
  'Main Title Theme Composer',
  'Story Editor',
  'Digital Conform Editor',
  'Genetator Operator',
  'Acting Double',
  'Weapons Master',
  'Standby Rigger',
  'Unit Medic',
  'Set Runner',
  'Floor Runner',
  'Dresser',
  'Insert Unit Director',
  'Department Administrator',
  'Chief Technician / Stop-Motion Expert',
  'Assistant Decorator',
  'Receptionist',
  'Shading',
  'Master at Arms',
  'Public Relations',
  'Sequence Leads',
  'Editorial Manager',
  'Additional Effects Development',
  'Key Scenic Artist',
  'Compositors',
  'Actor\'s Assistant',
  'Digital Intermediate Producer',
  'Video Assist Operator',
  'Digital Intermediate Editor',
  'Associate Editor',
  'Negative Cutter',
  'I/O Manager',
  'Draughtsman',
  'Key Grip',
  'Grip',
  'Assistant Grip',
  'Gaffer',
  'Production Manager',
  'Unit Production Manager',
  'Modeling',
  'Production Intern',
  'Mix Technician',
  'Visual Development',
  'Libra Head Technician',
  'Set Buyer',
  'Data Management Technician',
  'Seamstress',
  'Assistant Script',
  'Opening/Ending Animation',
  'Phantom Operator',
  'Action Director',
  '2D Artist',
  'Digital Intermediate',
  'Software Engineer',
  'Conceptual Illustrator',
  'Digital Imaging Technician',
  'Truck Costumer',
  'Main Title Designer',
  'Executive Story Editor',
  'Original Series Creator',
  'Supervising Editor',
  'Delegated Producer',
  'Researcher',
  'Title Designer',
  'Title Graphics',
  'Writers\' Assistant',
  'Chaperone',
  'Key Production Assistant',
  'Grip Production Assistant',
  'Key Grip Production Assistant',
  'Catering',
  'Production Executive',
  'Creative Producer',
  'Creature Technical Director',
  'Lead Character Designer',
  'Ultimate Arm Operator',
  'Location Sound Mixer',
  'Dressing Prop',
  'Focus Puller',
  'Assistant Production Manager',
  'Unit Manager',
  'Projection',
  'Pre-Visualization Coordinator',
  'Pre-Visualization Supervisor',
  'Assistant Unit Manager',
  'Drone Pilot',
  'Drone Operator',
  'Drone Cinematographer',
  'First Company Grip',
  'Digital Effects Producer',
  'Makeup Effects',
  'Generator Operator',
  'Tailor',
  'Loader',
  'Additional Editor',
  'Digital Compositor',
  'Studio Teacher',
  'Additional Grip',
  'Executive In Charge Of Production',
  'Contact Lens Technician',
  'Contact Lens Designer',
  'Motion Capture Artist',
  'Conceptual Design',
  'Legal Services',
  'Senior Modeller',
  'Craft Service',
  '24 Frame Playback',
  'Editorial Staff',
  'Production Office Assistant',
  'Character Designer',
  'Original Story',
  'Prop Designer',
  'Background Designer',
  'Wig Designer',
  'Conductor',
  'Color Designer',
  'Theme Song Performance',
  'Techno Crane Operator',
  'Russian Arm Operator',
  'Digital Intermediate Assistant',
  'Publicist',
  'Unit Publicist',
  'Comic Book',
  'Theatre Play',
  'Art Direction',
  'Crowd Assistant Director',
  'Administration',
  'Vocals',
  'Fix Animator',
  'Additional Editorial Assistant',
  'Photoscience Manager',
  'Human Resources',
  'Sign Painter',
  'Petty Cash Buyer',
  'Administrative Assistant',
  'Software Team Lead',
  'Story Manager',
  'Wigmaker',
  'Set Medic',
  'Sculptor',
  'First Assistant Editor',
  'Supervising Armorer',
  'Armorer',
  'Production Secretary',
  'Compositor',
  'Settings',
  'Utility Sound',
  'Ager/Dyer',
  'Director of Communications',
  'Tattoo Designer',
  'First Assistant Art Direction',
  'Opening Title Sequence',
  'Concept Artist',
  'Orchestrator',
  'Script Researcher',
  'Production Artist',
  'Simulation & Effects Production Assistant',
  'Supervising Producer',
  'Coordinating Producer',
  'Rotoscoping Artist',
  'Development Producer',
  'Leadman',
  'Head Greensman',
  'Greensman',
  'Graphic Designer',
  'Mechanical Designer',
  'Stand In',
  'Head of Research',
  'Research Assistant',
  'Health and Safety',
  'Other',
  'Thanks',
];

console.log(`role count: ${roles.length}`);

export default roles;