import $CastAndCrew from "./cast-and-crew.svelte";
import $Category from "./category.svelte";
import $ComingSoon from "./coming-soon.svelte";
import $FilmGrid from "./film-grid.svelte";
import $Filmopgraphy from "./filmography.svelte";
import $Films from "./films.svelte";
import $Genres from "./genres.svelte";
import $Header from "./header.svelte";
import $Navigation from "./navigation.svelte";
import $NowPlaying from "./now-playing.svelte";
import $People from "./people.svelte";
import $Poster from "./poster.svelte";
import $Recommendations from "./recommendations.svelte";
import $Search from "./search.svelte";

export const CastAndCrew = $CastAndCrew;
export const Category = $Category;
export const ComingSoon = $ComingSoon;
export const FilmGrid = $FilmGrid;
export const Filmopgraphy = $Filmopgraphy;
export const Films = $Films;
export const Genres = $Genres;
export const Header = $Header;
export const Navigation = $Navigation;
export const NowPlaying = $NowPlaying;
export const People = $People;
export const Poster = $Poster;
export const Recommendations = $Recommendations;
export const Search = $Search;